# Sample detection rules for Security Log Analyzer

anomaly_rules:
  - name: Impossible Travel
    description: Detect logins from distant geographic locations in short time windows
    threshold_minutes: 30
    severity: high

  - name: Multiple Failed Logins
    description: Detect more than N failed login attempts within time window
    threshold_count: 5
    time_window_minutes: 15
    severity: medium

  - name: Privilege Escalation
    description: Detect creation of new admin accounts or privilege grants
    monitored_actions:
      - CreateUser
      - AttachAdminPolicy
      - UpdateUserPermissions
    severity: critical

  - name: Suspicious IP Address
    description: Flag activity from known bad IP addresses
    ip_blocklist:
      - 185.100.87.202
      - 91.219.236.0/24
      - 45.155.205.0/24
    severity: high
